name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        head -1 private_key.pem
        eval $(ssh-agent -s)
        ssh-add private_key.pem
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /home/ec2-user/Phase2SWE || cd ~/Phase2SWE
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
        '
